# Git Abbreviations (expand on space)

abbr -a g git
abbr -a ga 'git add'
abbr -a gaa 'git add --all'
abbr -a gb 'git branch'
abbr -a gc 'git commit'
abbr -a gcm 'git commit -m'
abbr -a gco 'git checkout'
abbr -a gd 'git diff'
abbr -a gf 'git fetch'
abbr -a gl 'git log'
abbr -a gp 'git push'
abbr -a gpu 'git pull'
abbr -a gst 'git status'
abbr -a gm 'git merge'
abbr -a gr 'git remote'
abbr -a grb 'git rebase'
abbr -a grs 'git reset'
abbr -a grv 'git revert'